version: '3.9'

services:
  app:
    build: ./docker/php
    container_name: flowsync-app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000 & npm run dev"
    ports:
      - "8000:8000"
      - "5173:5173"
      - "6001:6001"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flowsync-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flowsync_pulse
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: